repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-yaml
        exclude: .clang-format
      - id: check-json
      - id: check-xml
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
        - id: clang-format
          args: ["-i"]
