camel:
  springboot.main-run-controller: true
  component:
    aws2-sns:
      overrideEndpoint: true
      uriEndpointOverride: http://localhost:4566
      message-group-id-strategy: useExchangeId
      secretKey: dummy_secret_key
      accessKey: dummy_access_key

alfresco:
  ingester:
    messaging:
        in.endpoint: activemq:topic:alfresco.repo.event2
        out.endpoint: aws2-sns://arn:aws:sns:us-east-1:000000000000:test-hxinsight-topic
